import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from './components/Navbar';
import { ChatProvider } from './context/AppContext';
// import { Merriweather, Inter } from 'next/font/google';



// const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

const inter = localFont({
  src: [
    {
      path: './fonts/Inter-Italic.woff2',
      weight: '400',
    },
    {
      path: './fonts/Inter-Italic.woff2',
      weight: '700',
    },
  ],
  variable: '--font-inter',
  display: 'swap',
});

const merriweather = localFont({
  src: [
    {
      path: './fonts/Merriweather-LightItalic.woff2',
      weight: '400',
    },
    {
      path: './fonts/Merriweather-Light.woff2',
      weight: '700',
    },
  ],
  variable: '--font-merriweather',
  display: 'swap',
});


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Agentic Appz",
  description: "Generated by JixAw.",
};

export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" 
    // className={`${inter.variable} ${merriweather.variable}`}
    >
      <body 
        className={`${inter.variable} ${merriweather.variable} antialiased`}
      >
        <ChatProvider>
        <Navbar />
        {children}
        </ChatProvider>
        
      </body>
    </html>
  );
}
